name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Exiftool
        uses: woss/exiftool-action@v12.87

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Install Playwright Browsers
        run: pnpm --filter nextjs-demo exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm --filter nextjs-demo exec playwright test
